import type { DailyEntry, Settings } from '@/types'
import { monthLabel } from '@/lib/date'
import {
  average,
  computeBMI,
  computeStreaks,
  round,
  sortedEntries,
  summarize,
} from '@/lib/calculations'

const HEADERS: (keyof DailyEntry)[] = [
  'date',
  'calories',
  'protein',
  'carbs',
  'fat',
  'weight',
  'water',
  'steps',
  'workoutMinutes',
  'notes',
]

function downloadBlob(content: BlobPart, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function exportCSV(entries: DailyEntry[]) {
  const rows = [HEADERS.join(',')]
  for (const e of entries) {
    rows.push(
      HEADERS.map((h) => {
        const v = e[h] ?? ''
        const s = String(v).replace(/"/g, '""')
        return /[,"\n]/.test(s) ? `"${s}"` : s
      }).join(',')
    )
  }
  downloadBlob(rows.join('\n'), `pulse-fitness-export-${Date.now()}.csv`, 'text/csv;charset=utf-8;')
}

export async function exportExcel(entries: DailyEntry[]) {
  const XLSX = await import('xlsx')
  const ws = XLSX.utils.json_to_sheet(entries.map((e) => Object.fromEntries(HEADERS.map((h) => [h, e[h] ?? '']))))
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, 'Entries')
  XLSX.writeFile(wb, `pulse-fitness-export-${Date.now()}.xlsx`)
}

export function exportJSON(entries: DailyEntry[]) {
  downloadBlob(JSON.stringify(entries, null, 2), `pulse-fitness-export-${Date.now()}.json`, 'application/json')
}

export function printPDFReport() {
  window.print()
}

// ---------- Downloadable reports ----------
// Opens a clean, print-ready report in a new tab and triggers the browser's
// print dialog so the user can "Save as PDF". No extra dependencies needed.

function openPrintableReport(title: string, bodyHtml: string) {
  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${title}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Inter, sans-serif; color: #1a2233; padding: 40px; max-width: 720px; margin: 0 auto; }
  h1 { font-size: 22px; margin-bottom: 2px; }
  .subtitle { color: #64748b; font-size: 13px; margin-bottom: 28px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.06em; color: #334155; margin: 28px 0 10px; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; }
  .stat { border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px 14px; }
  .stat .label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; margin-bottom: 4px; }
  .stat .value { font-size: 18px; font-weight: 600; font-family: 'JetBrains Mono', monospace; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 6px; }
  th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #f1f5f9; }
  th { color: #94a3b8; font-weight: 500; text-transform: uppercase; font-size: 10px; letter-spacing: 0.04em; }
  .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
${bodyHtml}
<p class="footer">Generated by Pulse — Fitness Analytics on ${new Date().toLocaleString()}</p>
<script>window.onload = () => setTimeout(() => window.print(), 300)</script>
</body>
</html>`)
  win.document.close()
}

function statBlock(label: string, value: string) {
  return `<div class="stat"><div class="label">${label}</div><div class="value">${value}</div></div>`
}

export function downloadMonthlyReport(
  allEntries: Record<string, DailyEntry>,
  settings: Settings,
  year: number,
  month: number
) {
  const monthEntries = Object.values(allEntries)
    .filter((e) => {
      const d = new Date(e.date + 'T00:00:00')
      return d.getFullYear() === year && d.getMonth() === month
    })
    .sort((a, b) => (a.date < b.date ? -1 : 1))

  const s = summarize(monthEntries, settings)
  const weights = monthEntries.map((e) => e.weight).filter((w): w is number => typeof w === 'number')
  const avgWeight = weights.length ? round(average(weights), 1) : null
  const totalWorkout = monthEntries.reduce((sum, e) => sum + e.workoutMinutes, 0)
  const totalSteps = monthEntries.reduce((sum, e) => sum + e.steps, 0)
  const label = monthLabel(year, month)

  const rows = monthEntries
    .map(
      (e) =>
        `<tr><td>${e.date}</td><td>${e.calories}</td><td>${e.protein}g</td><td>${e.carbs}g</td><td>${e.fat}g</td><td>${e.weight ?? '—'}</td><td>${e.steps}</td><td>${e.workoutMinutes}m</td></tr>`
    )
    .join('')

  openPrintableReport(
    `Pulse Report — ${label}`,
    `<h1>${label} Progress Report</h1>
     <p class="subtitle">${monthEntries.length} day${monthEntries.length === 1 ? '' : 's'} logged</p>
     <h2>Summary</h2>
     <div class="grid">
       ${statBlock('Avg Calories', `${s.avgCalories} kcal`)}
       ${statBlock('Avg Protein', `${s.avgProtein} g`)}
       ${statBlock('Avg Carbs', `${s.avgCarbs} g`)}
       ${statBlock('Avg Fat', `${s.avgFat} g`)}
       ${statBlock('Avg Weight', avgWeight != null ? `${avgWeight} kg` : '—')}
       ${statBlock('Protein Goal Hit', `${s.proteinGoalPct}%`)}
       ${statBlock('Total Workout', `${totalWorkout} min`)}
       ${statBlock('Total Steps', totalSteps.toLocaleString())}
       ${statBlock('Days Under Cal Goal', `${s.under1500}`)}
     </div>
     <h2>Daily Log</h2>
     <table>
       <thead><tr><th>Date</th><th>Cal</th><th>Protein</th><th>Carbs</th><th>Fat</th><th>Weight</th><th>Steps</th><th>Workout</th></tr></thead>
       <tbody>${rows || '<tr><td colspan="8">No entries logged this month.</td></tr>'}</tbody>
     </table>`
  )
}

export function downloadFullStatsReport(allEntries: Record<string, DailyEntry>, settings: Settings) {
  const list = sortedEntries(allEntries)
  const s = summarize(list, settings)
  const { current, longest } = computeStreaks(list)
  const weights = list.map((e) => e.weight).filter((w): w is number => typeof w === 'number')
  const latestWeight = weights.length ? weights[weights.length - 1] : null
  const bmi = latestWeight ? computeBMI(latestWeight, settings.heightCm) : 0
  const totalWorkout = list.reduce((sum, e) => sum + e.workoutMinutes, 0)
  const totalSteps = list.reduce((sum, e) => sum + e.steps, 0)
  const firstDate = list[0]?.date
  const lastDate = list[list.length - 1]?.date

  openPrintableReport(
    'Pulse — Full App Report',
    `<h1>Full Progress Report</h1>
     <p class="subtitle">${list.length} total days logged${firstDate ? ` &middot; ${firstDate} to ${lastDate}` : ''}</p>
     <h2>All-Time Averages</h2>
     <div class="grid">
       ${statBlock('Avg Calories', `${s.avgCalories} kcal`)}
       ${statBlock('Avg Protein', `${s.avgProtein} g`)}
       ${statBlock('Avg Carbs', `${s.avgCarbs} g`)}
       ${statBlock('Avg Fat', `${s.avgFat} g`)}
     </div>
     <h2>Activity</h2>
     <div class="grid">
       ${statBlock('Total Workout', `${totalWorkout} min`)}
       ${statBlock('Total Steps', totalSteps.toLocaleString())}
       ${statBlock('Current Streak', `${current} day${current === 1 ? '' : 's'}`)}
       ${statBlock('Longest Streak', `${longest} day${longest === 1 ? '' : 's'}`)}
     </div>
     <h2>Body</h2>
     <div class="grid">
       ${statBlock('Latest Weight', latestWeight != null ? `${latestWeight} kg` : '—')}
       ${statBlock('Goal Weight', `${settings.goalWeightKg} kg`)}
       ${statBlock('BMI', bmi ? `${bmi}` : '—')}
       ${statBlock('Protein Goal Hit', `${s.proteinGoalPct}% of days`)}
     </div>`
  )
}
